spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 'test'
      port: 123
      username: 'test'
      password: 'test'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:domain;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS test\;
    username: sa
    password:
    hikari:
      schema: 'test'

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

application:
  discord:
    webhook:
      url: 'test-webhook-url'