server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://grafana.ranchat.net/loki/api/v1/push
    tenant_id: ranchat-logs
scrape_configs:
  - job_name: system
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    static_configs:
      - targets:
          - localhost
        labels:
          job: ranchat-logs
          application: ranchat
          environment: ${ENVIRONMENT}
          __path__: /ranchat/logs/*.log